# Generated by Django 5.2.1 on 2025-05-12 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chat",
            name="chatroom",
        ),
        migrations.DeleteModel(
            name="ChatRoom",
        ),
    ]
